export const seedProducts = [
  {
    name: "Caykur Rize Tee",
    category: "Getranke",
    brand: "Caykur",
    description: "Traditioneller turkischer Schwarztee fur den klassischen Cay-Genuss.",
    image: "/assets/products/caykur-rize-tee.png",
    featured: true,
    available: true,
    unit: "500 g",
    origin: "Turkei",
    allergens: "",
    details: "Schwarzer Tee. Produktinformationen werden spater aus Etiketten oder Barcode-Daten erganzt.",
    barcode: "",
    tags: "tee,getranke"
  },
  {
    name: "Efepasa Sucuk",
    category: "Fleischwaren",
    brand: "Efepasa",
    description: "Wurzige turkische Knoblauchwurst, ideal zum Braten, Fruhstuck oder Grillen.",
    image: "/assets/products/efepasa-sucuk.png",
    featured: true,
    available: true,
    unit: "Packung",
    origin: "Deutschland",
    allergens: "",
    details: "Gekuhlt lagern. Details zu Zutaten und Allergenen werden je Produkt gepflegt.",
    barcode: "",
    tags: "fleisch,sucuk"
  },
  {
    name: "Baklava mit Pistazien",
    category: "Susswaren",
    brand: "Hausgemacht",
    description: "Traditionelles Geback mit feinen Pistazien und dunnen Teigschichten.",
    image: "/assets/products/baklava-pistazie.png",
    featured: true,
    available: true,
    unit: "nach Gewicht",
    origin: "Hausgemacht",
    allergens: "Nusse, Gluten",
    details: "Frisch aus der Theke. Ideal fur Feiern, Besuch und als Geschenk.",
    barcode: "",
    tags: "baklava,theke"
  },
  {
    name: "Sera Grune Oliven",
    category: "Konserven",
    brand: "Sera",
    description: "Eingelegte grune Oliven nach turkischer Art, aromatisch und mild.",
    image: "/assets/products/sera-gruene-oliven.png",
    featured: false,
    available: true,
    unit: "Glas",
    origin: "Turkei",
    allergens: "",
    details: "Eingelegte Oliven. Weitere Produktdaten konnen im Adminbereich gepflegt werden.",
    barcode: "",
    tags: "oliven,konserven"
  },
  {
    name: "Bagdat Pul Biber",
    category: "Gewurze",
    brand: "Bagdat",
    description: "Turkische Chiliflocken, scharf und aromatisch fur viele Gerichte.",
    image: "/assets/products/bagdat-pul-biber.png",
    featured: true,
    available: true,
    unit: "Packung",
    origin: "Turkei",
    allergens: "",
    details: "Gewurz fur Suppen, Grillgerichte und Pfannengerichte.",
    barcode: "",
    tags: "gewurz,scharf"
  },
  {
    name: "Yayla Ayran",
    category: "Milchprodukte",
    brand: "Yayla",
    description: "Erfrischendes Joghurtgetrank, passend zu warmen Speisen oder unterwegs.",
    image: "/assets/products/yayla-ayran.png",
    featured: true,
    available: true,
    unit: "Becher",
    origin: "Deutschland",
    allergens: "Milch",
    details: "Kuhl lagern. Beliebt zu Grillwaren, Brot und warmen Speisen.",
    barcode: "",
    tags: "ayran,milch"
  },
  {
    name: "Koska Tahin",
    category: "Fruhstuck",
    brand: "Koska",
    description: "Fein gemahlene Sesampaste, ideal fur Fruhstuck und Sussspeisen.",
    image: "/assets/products/koska-tahin.png",
    featured: false,
    available: true,
    unit: "Glas",
    origin: "Turkei",
    allergens: "Sesam",
    details: "Sesampaste fur Fruhstuck, Desserts und traditionelle Rezepte.",
    barcode: "",
    tags: "fruhstuck,sesam"
  },
  {
    name: "Koska Pekmez",
    category: "Fruhstuck",
    brand: "Koska",
    description: "Traditioneller Traubensirup, suss und naturlich im Geschmack.",
    image: "/assets/products/koska-pekmez.png",
    featured: false,
    available: true,
    unit: "Glas",
    origin: "Turkei",
    allergens: "",
    details: "Traubensirup. Wird haufig zusammen mit Tahin serviert.",
    barcode: "",
    tags: "fruhstuck,sirup"
  },
  {
    name: "Duru Bulgur",
    category: "Nudeln & Reis",
    brand: "Duru",
    description: "Klassischer Bulgur fur turkische Gerichte, Salate und Beilagen.",
    image: "/assets/products/duru-bulgur.png",
    featured: false,
    available: true,
    unit: "Packung",
    origin: "Turkei",
    allergens: "Gluten",
    details: "Bulgur fur Beilagen, Salate und warme Gerichte.",
    barcode: "",
    tags: "bulgur,reissortiment"
  }
];

export const seedOffer = {
  title: "Wochenangebot",
  description: "Aktuelle Angebote direkt aus dem Markt. Details im Laden oder per WhatsApp anfragen.",
  price: "ab 1,99 EUR",
  image: "/assets/hero.png",
  starts_at: "",
  ends_at: "",
  active: true
};
