export const seedProducts = [
  {
    name: "Çaykur Rize Tee",
    category: "Getränke",
    brand: "Çaykur",
    description: "Traditioneller türkischer Schwarztee für den klassischen Çay-Genuss.",
    image: "/assets/products/caykur-rize-tee.png",
    featured: true,
    available: true,
    unit: "500 g",
    origin: "Türkei",
    allergens: "",
    details: "Schwarzer Tee. Produktinformationen werden später aus Etiketten oder Barcode-Daten ergänzt.",
    barcode: "",
    tags: "tee,getränke"
  },
  {
    name: "Efepasa Sucuk",
    category: "Fleischwaren",
    brand: "Efepasa",
    description: "Würzige türkische Knoblauchwurst, ideal zum Braten, Frühstück oder Grillen.",
    image: "/assets/products/efepasa-sucuk.png",
    featured: true,
    available: true,
    unit: "Packung",
    origin: "Deutschland",
    allergens: "",
    details: "Gekühlt lagern. Details zu Zutaten und Allergenen werden je Produkt gepflegt.",
    barcode: "",
    tags: "fleisch,sucuk"
  },
  {
    name: "Baklava mit Pistazien",
    category: "Süßwaren",
    brand: "Hausgemacht",
    description: "Traditionelles Gebäck mit feinen Pistazien und dünnen Teigschichten.",
    image: "/assets/products/baklava-pistazie.png",
    featured: true,
    available: true,
    unit: "nach Gewicht",
    origin: "Hausgemacht",
    allergens: "Nüsse, Gluten",
    details: "Frisch aus der Theke. Ideal für Feiern, Besuch und als Geschenk.",
    barcode: "",
    tags: "baklava,theke"
  },
  {
    name: "Sera Grüne Oliven",
    category: "Konserven",
    brand: "Sera",
    description: "Eingelegte grüne Oliven nach türkischer Art, aromatisch und mild.",
    image: "/assets/products/sera-gruene-oliven.png",
    featured: false,
    available: true,
    unit: "Glas",
    origin: "Türkei",
    allergens: "",
    details: "Eingelegte Oliven. Weitere Produktdaten können im Adminbereich gepflegt werden.",
    barcode: "",
    tags: "oliven,konserven"
  },
  {
    name: "Bağdat Pul Biber",
    category: "Gewürze",
    brand: "Bağdat",
    description: "Türkische Chiliflocken, scharf und aromatisch für viele Gerichte.",
    image: "/assets/products/bagdat-pul-biber.png",
    featured: true,
    available: true,
    unit: "Packung",
    origin: "Türkei",
    allergens: "",
    details: "Gewürz für Suppen, Grillgerichte und Pfannengerichte.",
    barcode: "",
    tags: "gewürz,scharf"
  },
  {
    name: "Yayla Ayran",
    category: "Milchprodukte",
    brand: "Yayla",
    description: "Erfrischendes Joghurtgetränk, passend zu warmen Speisen oder unterwegs.",
    image: "/assets/products/yayla-ayran.png",
    featured: true,
    available: true,
    unit: "Becher",
    origin: "Deutschland",
    allergens: "Milch",
    details: "Kühl lagern. Beliebt zu Grillwaren, Brot und warmen Speisen.",
    barcode: "",
    tags: "ayran,milch"
  },
  {
    name: "Koska Tahin",
    category: "Frühstück",
    brand: "Koska",
    description: "Fein gemahlene Sesampaste, ideal für Frühstück und Süßspeisen.",
    image: "/assets/products/koska-tahin.png",
    featured: false,
    available: true,
    unit: "Glas",
    origin: "Türkei",
    allergens: "Sesam",
    details: "Sesampaste für Frühstück, Desserts und traditionelle Rezepte.",
    barcode: "",
    tags: "frühstück,sesam"
  },
  {
    name: "Koska Pekmez",
    category: "Frühstück",
    brand: "Koska",
    description: "Traditioneller Traubensirup, süß und natürlich im Geschmack.",
    image: "/assets/products/koska-pekmez.png",
    featured: false,
    available: true,
    unit: "Glas",
    origin: "Türkei",
    allergens: "",
    details: "Traubensirup. Wird häufig zusammen mit Tahin serviert.",
    barcode: "",
    tags: "frühstück,sirup"
  },
  {
    name: "Duru Bulgur",
    category: "Nudeln & Reis",
    brand: "Duru",
    description: "Klassischer Bulgur für türkische Gerichte, Salate und Beilagen.",
    image: "/assets/products/duru-bulgur.png",
    featured: false,
    available: true,
    unit: "Packung",
    origin: "Türkei",
    allergens: "Gluten",
    details: "Bulgur für Beilagen, Salate und warme Gerichte.",
    barcode: "",
    tags: "bulgur,reissortiment"
  }
];

export const seedOffer = {
  title: "Wochenangebot",
  description: "Aktuelle Angebote direkt aus dem Markt. Details im Laden oder per WhatsApp anfragen.",
  price: "ab 1,99 EUR",
  image: "/assets/hero.png",
  starts_at: "",
  ends_at: "",
  active: true
};
