/**
 * Entwürfe für Impressum und Datenschutz. Bewusst als Vorlage markiert:
 * Inhaberangaben ergänzen und vor Veröffentlichung prüfen (lassen).
 */
export function imprintTemplate(settings) {
  return [
    "Angaben gemäß § 5 DDG",
    "",
    "EFSE'Z Markt",
    "[Vor- und Nachname des Inhabers bzw. Firma und Rechtsform]",
    settings.address || "[Straße Hausnummer, PLZ Ort]",
    "",
    "Kontakt",
    `Telefon: ${settings.phone || "[Telefon]"}`,
    `E-Mail: ${settings.contact_email || "[E-Mail]"}`,
    "",
    "Umsatzsteuer-ID gemäß § 27a UStG: [falls vorhanden]",
    "Registereintrag: [falls vorhanden, z. B. Amtsgericht Nürnberg, HRA …]",
    "",
    "Verantwortlich für den Inhalt: [Name, Anschrift wie oben]",
    "",
    "Verbraucherstreitbeilegung: Wir sind nicht verpflichtet und nicht bereit, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen."
  ].join("\n");
}

export function privacyTemplate(settings) {
  return [
    "Der Schutz Ihrer persönlichen Daten ist uns wichtig. Hier erfahren Sie, welche Daten beim Besuch dieser Website verarbeitet werden, wofür und welche Rechte Sie haben. Kurz gesagt: Wir setzen keine Werbe- oder Analyse-Cookies ein, nutzen keine Tracking-Dienste und verkaufen keine Daten.",
    "",
    "1. Verantwortlicher",
    "",
    "Verantwortlich für die Datenverarbeitung auf dieser Website ist:",
    "EFSE'Z Markt (Inhaber und vollständige Angaben siehe Impressum)",
    settings.address || "[Straße Hausnummer, PLZ Ort]",
    `Telefon: ${settings.phone || "[Telefon]"}${settings.contact_email ? `\nE-Mail: ${settings.contact_email}` : ""}`,
    "",
    "Einen Datenschutzbeauftragten haben wir nicht benannt, weil wir dazu gesetzlich nicht verpflichtet sind. Bei Fragen zum Datenschutz wenden Sie sich bitte direkt an uns.",
    "",
    "2. Hosting und Aufruf der Website",
    "",
    "Diese Website wird bei Vercel Inc., 440 N Barranca Ave #4133, Covina, CA 91723, USA, gehostet. Wenn Sie die Website aufrufen, verarbeitet Vercel automatisch technisch notwendige Daten, die Ihr Browser übermittelt: IP-Adresse, Datum und Uhrzeit des Zugriffs, aufgerufene Seite, Referrer-URL, Browsertyp und Betriebssystem.",
    "",
    "Das ist nötig, um die Website auszuliefern, ihre Sicherheit und Stabilität zu gewährleisten und Missbrauch abzuwehren. Rechtsgrundlage ist unser berechtigtes Interesse an einem sicheren und funktionierenden Internetauftritt (Art. 6 Abs. 1 lit. f DSGVO). Die Protokolldaten werden nur kurzzeitig gespeichert und anschließend automatisch gelöscht.",
    "",
    "Mit Vercel besteht ein Vertrag zur Auftragsverarbeitung. Eine Übermittlung in die USA ist möglich; Vercel ist nach dem EU-US Data Privacy Framework zertifiziert (Angemessenheitsbeschluss der EU-Kommission, Art. 45 DSGVO). Zusätzlich gelten EU-Standardvertragsklauseln.",
    "",
    "3. Datenbank für Sortiment und Anfragen",
    "",
    "Unser Sortiment, unsere Angebote und die Nachrichten aus dem Kontaktformular speichern wir in einer Datenbank der Supabase Inc., 970 Toa Payoh North #07-04, Singapur 318992. Die Datenbank läuft auf Servern in Irland (EU). Mit Supabase besteht ein Vertrag zur Auftragsverarbeitung inklusive EU-Standardvertragsklauseln. Beim Anzeigen von Produkten und Bildern ruft Ihr Browser diese Daten direkt von dort ab; dabei wird technisch bedingt Ihre IP-Adresse übertragen (Art. 6 Abs. 1 lit. f DSGVO).",
    "",
    "4. Kontaktformular",
    "",
    "Wenn Sie uns über das Kontaktformular schreiben, speichern wir Ihre Angaben: Name (freiwillig), Telefonnummer oder E-Mail-Adresse, das gewählte Anliegen und Ihre Nachricht sowie den Zeitpunkt der Anfrage. Wir nutzen diese Daten ausschließlich, um Ihre Anfrage zu bearbeiten und Ihnen zu antworten.",
    "",
    "Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO, wenn Ihre Anfrage mit einem Einkauf oder einer Bestellung zusammenhängt, sonst unser berechtigtes Interesse an der Beantwortung von Anfragen (Art. 6 Abs. 1 lit. f DSGVO). Wir löschen Ihre Angaben, sobald Ihre Anfrage abschließend bearbeitet ist und keine gesetzlichen Aufbewahrungspflichten entgegenstehen. Die Angaben sind freiwillig; ohne Kontaktmöglichkeit können wir Ihnen allerdings nicht antworten.",
    "",
    "5. Kontakt per Telefon, E-Mail oder WhatsApp",
    "",
    "Wenn Sie uns anrufen, eine E-Mail schreiben oder uns per WhatsApp kontaktieren, verarbeiten wir Ihre Kontaktdaten und den Inhalt Ihrer Nachricht, um Ihr Anliegen zu bearbeiten (Art. 6 Abs. 1 lit. b bzw. lit. f DSGVO).",
    "",
    "Die WhatsApp-Knöpfe auf unserer Website sind einfache Links. Beim bloßen Besuch der Website werden keine Daten an WhatsApp übertragen. Erst wenn Sie einen WhatsApp-Knopf antippen, öffnet sich WhatsApp, ein Dienst der WhatsApp Ireland Limited, Merrion Road, Dublin 4, D04 X2K5, Irland (Teil von Meta). Für die Nutzung von WhatsApp gelten die Datenschutzbestimmungen von WhatsApp; dabei können Daten auch in die USA übermittelt werden. Wenn Sie das nicht möchten, erreichen Sie uns jederzeit auch telefonisch oder über das Kontaktformular.",
    "",
    "6. Google Maps",
    "",
    "Auf unserer Website zeigen wir unseren Standort mit einer Karte von Google Maps. Anbieter ist die Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland.",
    "",
    "Die Karte wird erst geladen, wenn Sie auf „Karte laden“ klicken. Vorher werden keine Daten an Google übertragen. Mit dem Klick willigen Sie ein, dass Ihr Browser eine Verbindung zu Google aufbaut. Dabei werden unter anderem Ihre IP-Adresse und Informationen über die aufgerufene Seite an Google übertragen, und Google kann Cookies oder ähnliche Technologien einsetzen. Eine Übermittlung in die USA ist möglich; Google ist nach dem EU-US Data Privacy Framework zertifiziert.",
    "",
    "Rechtsgrundlage ist Ihre Einwilligung (Art. 6 Abs. 1 lit. a DSGVO und § 25 Abs. 1 TDDDG). Die Einwilligung gilt nur für den aktuellen Seitenaufruf und wird nicht gespeichert. Beim nächsten Besuch ist die Karte wieder ausgeblendet. Mehr Informationen: https://policies.google.com/privacy",
    "",
    "Der Link „Route planen“ öffnet Google Maps in einem neuen Fenster. Auch hier werden erst mit dem Klick Daten an Google übertragen.",
    "",
    "7. Cookies und Speicherung im Browser",
    "",
    "Wir setzen keine Cookies zu Werbe-, Analyse- oder Marketingzwecken ein. Damit die Seite schneller lädt, speichert Ihr Browser das Sortiment kurzzeitig im sogenannten Sitzungsspeicher (Session Storage). Diese Daten enthalten keine Angaben zu Ihrer Person und werden automatisch gelöscht, sobald Sie den Tab oder Browser schließen. Diese Speicherung ist für den von Ihnen gewünschten Dienst unbedingt erforderlich (§ 25 Abs. 2 Nr. 2 TDDDG).",
    "",
    "Für unseren internen Personalbereich wird nach der Anmeldung ein Anmelde-Token im Browser gespeichert. Das betrifft nur unsere Mitarbeiter, nicht die Besucher der Website.",
    "",
    "8. Schriftarten",
    "",
    "Die Schriftarten dieser Website werden von unserem eigenen Server geladen. Es findet keine Verbindung zu Google Fonts oder anderen Schriftanbietern statt.",
    "",
    "9. Verschlüsselung",
    "",
    "Diese Website nutzt aus Sicherheitsgründen eine SSL- bzw. TLS-Verschlüsselung. Eine verschlüsselte Verbindung erkennen Sie an „https://“ und dem Schloss-Symbol in der Adresszeile Ihres Browsers.",
    "",
    "10. Ihre Rechte",
    "",
    "Sie haben jederzeit das Recht auf:",
    "• Auskunft über Ihre bei uns gespeicherten Daten (Art. 15 DSGVO)",
    "• Berichtigung unrichtiger Daten (Art. 16 DSGVO)",
    "• Löschung Ihrer Daten (Art. 17 DSGVO)",
    "• Einschränkung der Verarbeitung (Art. 18 DSGVO)",
    "• Datenübertragbarkeit (Art. 20 DSGVO)",
    "• Widerruf einer erteilten Einwilligung mit Wirkung für die Zukunft (Art. 7 Abs. 3 DSGVO)",
    "",
    "Widerspruchsrecht: Soweit wir Daten auf Grundlage unseres berechtigten Interesses (Art. 6 Abs. 1 lit. f DSGVO) verarbeiten, können Sie dieser Verarbeitung aus Gründen, die sich aus Ihrer besonderen Situation ergeben, jederzeit widersprechen (Art. 21 DSGVO).",
    "",
    "Wenden Sie sich dafür einfach an die oben genannten Kontaktdaten.",
    "",
    "Außerdem haben Sie das Recht, sich bei einer Datenschutz-Aufsichtsbehörde zu beschweren. Für uns zuständig ist das Bayerische Landesamt für Datenschutzaufsicht (BayLDA), Promenade 18, 91522 Ansbach, www.lda.bayern.de.",
    "",
    "11. Änderungen",
    "",
    "Wir passen diese Datenschutzerklärung an, wenn sich die Website oder die rechtlichen Vorgaben ändern. Es gilt die jeweils hier veröffentlichte Fassung.",
    "",
    "Stand: " + new Date().toLocaleDateString("de-DE", { month: "long", year: "numeric" })
  ].join("\n");
}
